# Generated by Django 2.1.8 on 2019-07-25 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0002_auto_20190725_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='buyer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Buyer.Buyer', verbose_name='用户id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='post_number',
            field=models.CharField(default=1, max_length=32, verbose_name='邮编'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='recv_phone',
            field=models.CharField(default=1, max_length=32, verbose_name='收件人电话'),
            preserve_default=False,
        ),
    ]
