# Generated by Django 2.1.8 on 2019-07-29 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0003_auto_20190725_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=32, verbose_name='id订单编号')),
                ('goods_count', models.IntegerField(verbose_name='商品订单数量')),
                ('order_price', models.FloatField(verbose_name='订单总价')),
                ('order_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.Address', verbose_name='订单地址')),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.Buyer', verbose_name='订单用户')),
            ],
        ),
        migrations.CreateModel(
            name='Ordertail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Good_id', models.IntegerField(verbose_name='商品id')),
                ('Good_name', models.CharField(max_length=32, verbose_name='商品名称')),
                ('Good_price', models.FloatField(verbose_name='商品价格')),
                ('Good_number', models.IntegerField(verbose_name='商品购买数量')),
                ('Good_total', models.FloatField(verbose_name='商品总价')),
                ('Good_store', models.IntegerField(verbose_name='商品id')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.Order', verbose_name='订单用户（多对一）')),
            ],
        ),
    ]
