# Generated by Django 2.1.8 on 2019-07-29 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0004_order_ordertail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordertail',
            old_name='Good_id',
            new_name='good_id',
        ),
        migrations.RenameField(
            model_name='ordertail',
            old_name='Good_name',
            new_name='good_name',
        ),
        migrations.RenameField(
            model_name='ordertail',
            old_name='Good_number',
            new_name='good_number',
        ),
        migrations.RenameField(
            model_name='ordertail',
            old_name='Good_price',
            new_name='good_price',
        ),
        migrations.RenameField(
            model_name='ordertail',
            old_name='Good_store',
            new_name='good_store',
        ),
        migrations.RenameField(
            model_name='ordertail',
            old_name='Good_total',
            new_name='good_total',
        ),
    ]
