# Generated by Django 2.1.8 on 2019-07-29 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0005_auto_20190729_1136'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ordertail',
            new_name='OrderDetail',
        ),
    ]
